import { 
  OrgRole, 
  OrgUser, 
  JobPosting, 
  CandidateApplication, 
  TokenTransaction, 
  OrganisationProfile,
  ApplicationStage 
} from '../types/organization.types';

// Mock Organisation Info
export const MOCK_ORG: OrganisationProfile = {
  id: 'org_acme_corp',
  name: 'Acme Technologies Inc.',
  logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&q=80',
  domain: 'acmetech.io',
  industry: 'Enterprise Software & AI',
  size: '250 - 500 Employees',
  totalTokensBalance: 4850,
  allocatedTokensTotal: 2100,
  usedTokensTotal: 1250,
  subscriptionPlan: 'PRO_ENTERPRISE',
};

// Initial Mock Users
export const INITIAL_MEMBERS: OrgUser[] = [
  {
    id: 'u_1',
    name: 'Sarah Jenkins',
    email: 'sarah.j@acmetech.io',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80',
    role: 'ORG_SUPER_ADMIN',
    title: 'VP of Talent Acquisition',
    allocatedTokens: 1500,
    usedTokens: 450,
    activeJobsCount: 4,
    status: 'ACTIVE',
  },
  {
    id: 'u_2',
    name: 'Marcus Vance',
    email: 'marcus.v@acmetech.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80',
    role: 'ORG_ADMIN',
    title: 'HR Director',
    allocatedTokens: 1000,
    usedTokens: 300,
    activeJobsCount: 3,
    status: 'ACTIVE',
  },
  {
    id: 'u_3',
    name: 'Elena Rostova',
    email: 'elena.r@acmetech.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80',
    role: 'HR_RECRUITER',
    title: 'Senior Technical Recruiter',
    allocatedTokens: 600,
    usedTokens: 250,
    activeJobsCount: 5,
    status: 'ACTIVE',
  },
  {
    id: 'u_4',
    name: 'David Chen',
    email: 'david.c@acmetech.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&q=80',
    role: 'TECH_RECRUITER',
    title: 'Engineering Lead & Hiring Partner',
    allocatedTokens: 450,
    usedTokens: 150,
    activeJobsCount: 2,
    status: 'ACTIVE',
  },
  {
    id: 'u_5',
    name: 'Priya Sharma',
    email: 'priya.s@acmetech.io',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=120&q=80',
    role: 'HIRING_MANAGER',
    title: 'Product Management Director',
    allocatedTokens: 300,
    usedTokens: 100,
    activeJobsCount: 1,
    status: 'ACTIVE',
  },
];

// Initial Mock Job Postings
export const INITIAL_JOBS: JobPosting[] = [
  {
    id: 'job_101',
    title: 'Senior Full Stack Engineer (React + Node.js)',
    department: 'Engineering',
    location: 'San Francisco, CA / Remote',
    workMode: 'HYBRID',
    type: 'FULL_TIME',
    status: 'PUBLISHED',
    tokensCost: 50,
    recruiterId: 'u_3',
    recruiterName: 'Elena Rostova',
    applicantsCount: 42,
    shortlistedCount: 8,
    createdAt: '2026-09-20',
    description: 'We are seeking an experienced Full Stack Architect to build out multi-tenant microservices and real-time dashboard systems.',
    skillsRequired: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Tailwind CSS', 'Redis'],
  },
  {
    id: 'job_102',
    title: 'Lead AI / ML Pipeline Engineer',
    department: 'AI Research & Data',
    location: 'Austin, TX / Remote',
    workMode: 'REMOTE',
    type: 'FULL_TIME',
    status: 'PUBLISHED',
    tokensCost: 75,
    recruiterId: 'u_4',
    recruiterName: 'David Chen',
    applicantsCount: 28,
    shortlistedCount: 5,
    createdAt: '2026-09-22',
    description: 'Join our AI infrastructure core team integrating Google Gemini LLM API and BullMQ queue pipelines for automated resume parsing.',
    skillsRequired: ['Python', 'Gemini API', 'PyTorch', 'NestJS', 'BullMQ', 'OpenSearch'],
  },
  {
    id: 'job_103',
    title: 'Senior Product Manager - Platform SaaS',
    department: 'Product',
    location: 'New York, NY',
    workMode: 'ON_SITE',
    type: 'FULL_TIME',
    status: 'PUBLISHED',
    tokensCost: 50,
    recruiterId: 'u_5',
    recruiterName: 'Priya Sharma',
    applicantsCount: 19,
    shortlistedCount: 4,
    createdAt: '2026-09-24',
    description: 'Drive multi-tenant platform features, token economy pricing models, and corporate recruitment workflows.',
    skillsRequired: ['Product Strategy', 'SaaS Metrics', 'User Research', 'Agile/Scrum', 'Analytics'],
  },
  {
    id: 'job_104',
    title: 'Staff DevOps & Infrastructure Architect',
    department: 'DevOps & Security',
    location: 'Remote',
    workMode: 'REMOTE',
    type: 'CONTRACT',
    status: 'PAUSED',
    tokensCost: 50,
    recruiterId: 'u_2',
    recruiterName: 'Marcus Vance',
    applicantsCount: 14,
    shortlistedCount: 2,
    createdAt: '2026-09-15',
    description: 'Architect multi-region AWS ECS clusters, Docker pipelines, and OpenTelemetry observability frameworks.',
    skillsRequired: ['AWS ECS', 'Docker', 'Terraform', 'Prometheus', 'Grafana', 'GitHub Actions'],
  },
];

// Initial Candidate Applications
export const INITIAL_CANDIDATES: CandidateApplication[] = [
  {
    id: 'cand_1',
    candidateName: 'Alex Rivers',
    candidateEmail: 'alex.rivers@devmail.com',
    candidatePhone: '+1 (555) 349-2011',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=120&q=80',
    jobId: 'job_101',
    jobTitle: 'Senior Full Stack Engineer (React + Node.js)',
    matchScore: 96,
    appliedDate: '2026-09-25',
    stage: 'INTERVIEW_SCHEDULED',
    resumeUrl: '#',
    aiSummary: 'Top match: 7+ years in TypeScript, NestJS, and React. Architected high-throughput microservices. Excellent match for Acme tech stack.',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Redis', 'Docker'],
    experienceYears: 7,
    expectedSalary: '$165,000 / yr',
    recruiterNotes: 'Passed technical screening. Round 2 System Architecture scheduled.',
    interviewDate: '2026-09-29 14:00 EST',
  },
  {
    id: 'cand_2',
    candidateName: 'Sophia Lin',
    candidateEmail: 'sophia.lin@ai-research.io',
    candidatePhone: '+1 (555) 912-8843',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=120&q=80',
    jobId: 'job_102',
    jobTitle: 'Lead AI / ML Pipeline Engineer',
    matchScore: 94,
    appliedDate: '2026-09-26',
    stage: 'SHORTLISTED',
    resumeUrl: '#',
    aiSummary: 'Extensive experience fine-tuning LLMs, Gemini API integration, and setting up BullMQ background workers.',
    skills: ['Gemini API', 'Python', 'NestJS', 'BullMQ', 'OpenSearch', 'Vector Databases'],
    experienceYears: 6,
    expectedSalary: '$180,000 / yr',
    recruiterNotes: 'Strong candidate profile. Resume parser scored 94%.',
  },
  {
    id: 'cand_3',
    candidateName: 'Marcus Brodie',
    candidateEmail: 'm.brodie@cloudnet.org',
    candidatePhone: '+1 (555) 441-0092',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=120&q=80',
    jobId: 'job_101',
    jobTitle: 'Senior Full Stack Engineer (React + Node.js)',
    matchScore: 88,
    appliedDate: '2026-09-24',
    stage: 'SCREENING',
    resumeUrl: '#',
    aiSummary: 'Solid frontend focus with React 18, Tailwind CSS, and TanStack Query. Learning backend NestJS.',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Redux', 'GraphQL'],
    experienceYears: 5,
    expectedSalary: '$150,000 / yr',
  },
  {
    id: 'cand_4',
    candidateName: 'Rachel Vance',
    candidateEmail: 'rvance@productmasters.com',
    candidatePhone: '+1 (555) 778-1204',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&q=80',
    jobId: 'job_103',
    jobTitle: 'Senior Product Manager - Platform SaaS',
    matchScore: 91,
    appliedDate: '2026-09-27',
    stage: 'OFFER_EXTENDED',
    resumeUrl: '#',
    aiSummary: 'Proven SaaS PM with background in multi-tenant B2B monetization and credit system pricing.',
    skills: ['Product Strategy', 'SaaS Metrics', 'User Research', 'SQL', 'Mixpanel'],
    experienceYears: 8,
    expectedSalary: '$175,000 / yr',
    recruiterNotes: 'Offer extended on Sep 27. Pending candidate signature.',
  },
  {
    id: 'cand_5',
    candidateName: 'Daniel Kim',
    candidateEmail: 'daniel.kim@devops.co',
    candidatePhone: '+1 (555) 654-9981',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=120&q=80',
    jobId: 'job_104',
    jobTitle: 'Staff DevOps & Infrastructure Architect',
    matchScore: 82,
    appliedDate: '2026-09-21',
    stage: 'APPLIED',
    resumeUrl: '#',
    aiSummary: 'Kubernetes specialist with AWS certification. Good background in container security.',
    skills: ['AWS', 'Kubernetes', 'Docker', 'Jenkins', 'Terraform'],
    experienceYears: 9,
    expectedSalary: '$190,000 / yr',
  }
];

// Initial Token Ledger Transactions
export const INITIAL_TRANSACTIONS: TokenTransaction[] = [
  {
    id: 'tx_901',
    type: 'PURCHASE',
    amount: 5000,
    performedBy: 'Sarah Jenkins (Super Admin)',
    description: 'Purchased Enterprise Pro Token Bundle via Razorpay',
    timestamp: '2026-09-01 10:30 AM',
  },
  {
    id: 'tx_902',
    type: 'ALLOCATION',
    amount: 600,
    allocatedTo: 'Elena Rostova (HR Recruiter)',
    performedBy: 'Marcus Vance (Admin)',
    description: 'Monthly recruiter token quota allocation',
    timestamp: '2026-09-05 09:15 AM',
  },
  {
    id: 'tx_903',
    type: 'CONSUMPTION_JOB_POST',
    amount: -75,
    performedBy: 'David Chen (Tech Recruiter)',
    description: 'Posted Job #102: Lead AI / ML Pipeline Engineer',
    timestamp: '2026-09-22 14:20 PM',
  },
  {
    id: 'tx_904',
    type: 'CONSUMPTION_RESUME_PARSER',
    amount: -25,
    performedBy: 'Elena Rostova (HR Recruiter)',
    description: 'AI Batch Resume Parsing & Skill Extraction (5 Candidates)',
    timestamp: '2026-09-26 11:45 AM',
  },
];
